version: '3'

tasks:
  init-db:
    desc: "Start ClickHouse and create the marketplace_data table"
    cmds:
      - |
        # Start ClickHouse container in detached mode
        docker run -d -p 18123:8123 -p19000:9000 --name some-clickhouse-server --ulimit nofile=262144:262144 clickhouse/clickhouse-server

        # Wait for ClickHouse to start up
        sleep 5

        # Run init_db.sql to initialize the database
        docker exec -i some-clickhouse-server clickhouse-client --multiquery < sql/init_db.sql

        # Run marketplace_schema.sql to create the marketplace_data table
        docker exec -i some-clickhouse-server clickhouse-client --multiquery < sql/marketplace_schema.sql

  shutdown-db:
    desc: "Stop and remove the ClickHouse container"
    cmds:
      - |
        # Stop the ClickHouse container
        docker stop some-clickhouse-server || echo "Container not running."

        # Remove the ClickHouse container
        docker rm some-clickhouse-server || echo "Container does not exist."
